spring.application.name=temp-inc-detector
spring.config.import=configserver:http://localhost:8888
spring.cloud.stream.binders.kafka.type=kstream
spring.cloud.stream.binders.kafka.environment.spring.cloud.stream.kafka.streams.binder.brokers=localhost:29092
spring.kafka.streams.properties.spring.json.use.type.headers=false
spring.cloud.stream.kafka.streams.binder.deserialization-exception-handler=logandcontinue

spring.cloud.stream.function.definition=processor

spring.cloud.stream.kafka.streams.binder.functions.anomalyDetectorProcessor.application-id=temp-inc-detector
spring.cloud.stream.bindings.processor-in-0.content-type=application/json
spring.cloud.stream.bindings.processor-in-0.destination=temperature-measurements
spring.cloud.stream.bindings.processor-in-0.binder=kafka

spring.cloud.stream.bindings.processor-out-0.content-type=application/json
spring.cloud.stream.bindings.processor-out-0.destination=temperature-anomalies
spring.cloud.stream.bindings.processor-out-0.binder=kafka
