spring:
  application:
    name: 'temp-inc-analytics-api'
  data:
    rest:
      detection-strategy: annotated
  jackson:
    serialization:
      INDENT_OUTPUT: true
project:
  version: @project.version@
server:
  port: 8083
  error:
    include-message: always
  servlet:
    context-path: '/api'
springdoc:
  show-actuator: false
