spring:
  application:
    name: 'temp-inc-config-server'
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:configuration
server:
  port: 8888
